#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  OpenClawd — One-Shot Installer
#  Installs: Chrome Extension + Page Agent + MCP Bridge
#  Connects to: OpenClawd orchestrator, SolanaOS daemon
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

# This script lives inside chrome-extension/, so the repo root is one level up.
EXT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$EXT_DIR/.." && pwd)"
# Solana-tools MCP server (Helius/Jupiter/etc) — has its own package.json + tsc build.
MCP_DIR="$REPO_ROOT/mcp"
# Browser-MCP bridge that talks to the chrome extension (no build step, plain ESM).
EXT_MCP_DIR="$EXT_DIR/mcp"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color
BOLD='\033[1m'

echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║   🦞  O P E N C L A W D  —  pAGENT Browser Agent            ║"
echo "║                                                              ║"
echo "║   The Hermes of Web3 • AI Agent Browser                      ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Step 1: Check prerequisites ──────────────────────────────────
echo -e "\n${BOLD}🔍 Checking prerequisites...${NC}"

require_command() {
  if command -v "$1" &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} $1 found"
  else
    echo -e "  ${RED}✗${NC} $1 not found — please install it and re-run." >&2
    exit 1
  fi
}

optional_command() {
  if command -v "$1" &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} $1 found"
  else
    echo -e "  ${YELLOW}⚠${NC} $1 not found (optional)"
  fi
}

require_command "node"
require_command "npm"
optional_command "git"

# ── Step 2: Build Chrome Extension ────────────────────────────────
echo -e "\n${BOLD}🔨 Building Chrome Extension...${NC}"

cd "$EXT_DIR" || exit 1

# Create build directory
mkdir -p build
rm -rf build/*

# Copy essential files
echo -e "  ${BLUE}→${NC} Copying extension files..."
cp manifest.json build/
cp popup.html build/
cp popup.css build/
cp popup.js build/
cp background.js build/

# Copy icons
mkdir -p build/icons
cp -r icons/*.png build/icons/ 2>/dev/null || true

# Copy clawd-agent (page agent)
cp -r clawd-agent build/

echo -e "  ${GREEN}✓${NC} Extension built at: $EXT_DIR/build/"

# ── Step 3: Build & Start OpenClawd Solana-tools MCP ─────────────
echo -e "\n${BOLD}🚀 Preparing OpenClawd MCP servers...${NC}"

MCP_PID=""
ORCH_ENTRY="$MCP_DIR/dist/index.js"

if [ -d "$MCP_DIR" ] && [ -f "$MCP_DIR/package.json" ]; then
  cd "$MCP_DIR" || exit 1

  if [ ! -d node_modules ]; then
    echo -e "  ${BLUE}→${NC} Installing $MCP_DIR dependencies..."
    npm install --no-audit --no-fund
  fi

  if [ ! -f "$ORCH_ENTRY" ] || [ "$MCP_DIR/src/index.ts" -nt "$ORCH_ENTRY" ]; then
    echo -e "  ${BLUE}→${NC} Building Solana-tools MCP (tsc)..."
    npm run build
  fi

  if [ -f "$ORCH_ENTRY" ]; then
    LOG_DIR="$REPO_ROOT/.logs"
    mkdir -p "$LOG_DIR"
    echo -e "  ${BLUE}→${NC} Starting Solana-tools MCP in background..."
    nohup node "$ORCH_ENTRY" > "$LOG_DIR/openclawd-mcp.log" 2>&1 &
    MCP_PID=$!
    echo "$MCP_PID" > "$REPO_ROOT/.openclawd-mcp.pid"

    sleep 1
    if kill -0 "$MCP_PID" 2>/dev/null; then
      echo -e "  ${GREEN}✓${NC} Solana-tools MCP running (PID: $MCP_PID, log: $LOG_DIR/openclawd-mcp.log)"
    else
      echo -e "  ${YELLOW}⚠${NC} Solana-tools MCP exited immediately — check $LOG_DIR/openclawd-mcp.log"
      MCP_PID=""
    fi
  else
    echo -e "  ${RED}✗${NC} Build did not produce $ORCH_ENTRY — skipping MCP launch." >&2
  fi
else
  echo -e "  ${YELLOW}⚠${NC} $MCP_DIR not found; skipping Solana-tools MCP startup."
fi

# Browser-MCP deps (ESM; no build step needed, but it does need its node_modules).
if [ -d "$EXT_MCP_DIR" ] && [ -f "$EXT_MCP_DIR/package.json" ] && [ ! -d "$EXT_MCP_DIR/node_modules" ]; then
  echo -e "  ${BLUE}→${NC} Installing browser-MCP dependencies..."
  ( cd "$EXT_MCP_DIR" && npm install --no-audit --no-fund ) || \
    echo -e "  ${YELLOW}⚠${NC} Browser-MCP install failed; the openclawd-browser MCP server may not start."
fi

# ── Step 4: Generate Chrome Extension Config ─────────────────────
echo -e "\n${BOLD}⚙️  Generating extension config...${NC}"

cat > "$EXT_DIR/build/openclawd-config.js" << 'EOFCONFIG'
// OpenClawd Extension Configuration
// Auto-generated by one-shot installer

const OPENCLAWD_CONFIG = {
  version: '3.0.0',
  
  // MCP Bridge (OpenClawd orchestrator)
  mcpBridge: {
    port: 3001,
    url: 'http://localhost:3001',
  },
  
  // Gateway (SolanaOS daemon)
  gateway: {
    default: 'http://127.0.0.1:18790',
    candidates: [
      'http://127.0.0.1:18790',
      'http://127.0.0.1:7777',
      'http://localhost:18790',
      'http://localhost:7777',
    ],
  },
  
  // Wallet API (agent-wallet service)
  walletApi: {
    port: 8421,
    url: 'http://localhost:8421',
  },
  
  // MawdAxe Mining Fleet
  mawdaxe: {
    port: 8420,
    url: 'http://localhost:8420',
  },
  
  // LLM Providers
  llm: {
    defaultProvider: 'openrouter',
    defaultModel: 'anthropic/claude-sonnet-4-6',
    providers: ['openrouter', 'anthropic', 'xai', 'ollama'],
  },
  
  // Agent Harness Integration
  harness: {
    enabled: true,
    catalogUrl: 'https://hub.solanaclawd.com',
    agentsPath: '/agents',
    skillsPath: '/skills',
  },
  
  // SolanaOS Binary Connection
  solanaos: {
    binaryPath: 'openclawd',
    configPath: '~/.openclawdsolana/config.json',
    gatewayPort: 18790,
    controlUIPort: 7777,
  },
  
  // $CLAWD Token (tier gating)
  clawdToken: {
    mint: '8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump',
    pumpFunUrl: 'https://pump.fun/8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump',
  },
  
  // OpenClawd Links
  links: {
    hub: 'https://hub.solanaclawd.com',
    website: 'https://solanaclawd.com',
    docs: 'https://docs.solanaclawd.com',
    github: 'https://github.com/clawdsolana/OpenClawd',
  },
};

if (typeof window !== 'undefined') {
  window.OPENCLAWD_CONFIG = OPENCLAWD_CONFIG;
}
EOFCONFIG

echo -e "  ${GREEN}✓${NC} Config generated"

# ── Step 5: Merge Claude Desktop Config ──────────────────────────
echo -e "\n${BOLD}📝 Updating Claude Desktop MCP config...${NC}"

CLAUDE_CONFIG_DIR="$HOME/Library/Application Support/Claude"
CLAUDE_CONFIG_FILE="$CLAUDE_CONFIG_DIR/claude_desktop_config.json"
mkdir -p "$CLAUDE_CONFIG_DIR"

BROWSER_ENTRY="$EXT_MCP_DIR/src/index.js"

# Build the two server entries we want to register.
NEW_SERVERS=$(cat <<EOFSERVERS
{
  "openclawd": {
    "command": "node",
    "args": ["$ORCH_ENTRY"],
    "env": {
      "OPENCLAWD_GATEWAY_URL": "http://localhost:18790",
      "OPENCLAWD_MCP_PORT": "3001"
    }
  },
  "openclawd-browser": {
    "command": "node",
    "args": ["$BROWSER_ENTRY"],
    "env": {
      "LLM_BASE_URL": "https://openrouter.ai/api/v1",
      "LLM_MODEL_NAME": "anthropic/claude-sonnet-4-6"
    }
  }
}
EOFSERVERS
)

if [ -f "$CLAUDE_CONFIG_FILE" ]; then
  BACKUP="$CLAUDE_CONFIG_FILE.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$CLAUDE_CONFIG_FILE" "$BACKUP"
  echo -e "  ${BLUE}→${NC} Backed up existing config to $BACKUP"
fi

if command -v node &> /dev/null; then
  node - "$CLAUDE_CONFIG_FILE" "$NEW_SERVERS" <<'EOFNODE'
const fs = require('fs');
const [, , configPath, newServersJson] = process.argv;
let existing = {};
if (fs.existsSync(configPath)) {
  try {
    existing = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  } catch (e) {
    console.error('  Existing config is not valid JSON; aborting merge to avoid data loss.');
    process.exit(1);
  }
}
const additions = JSON.parse(newServersJson);
existing.mcpServers = { ...(existing.mcpServers || {}), ...additions };
fs.writeFileSync(configPath, JSON.stringify(existing, null, 2) + '\n');
EOFNODE
  echo -e "  ${GREEN}✓${NC} Claude Desktop config merged (existing servers preserved)"
else
  echo -e "  ${YELLOW}⚠${NC} node not available; skipped Claude Desktop config merge"
fi

# ── Step 6: Print Instructions ────────────────────────────────────
echo -e "\n${PURPLE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}✅ Installation Complete!${NC}"
echo -e "${PURPLE}═══════════════════════════════════════════════════════════════${NC}"

echo -e "\n${BOLD}📦 Extension Location:${NC}"
echo -e "  ${BLUE}→${NC} Load unpacked: $EXT_DIR/build/"
echo -e "  ${BLUE}→${NC} Load pAGENT: $EXT_DIR/build/clawd-agent/"

echo -e "\n${BOLD}🔧 How to Install Extension:${NC}"
echo -e "  1. Open chrome://extensions/"
echo -e "  2. Enable Developer mode (top-right toggle)"
echo -e "  3. Click 'Load unpacked'"
echo -e "  4. Select: $EXT_DIR/build/"
echo -e "  5. Click the 🦞 icon in your toolbar"

echo -e "\n${BOLD}🦞 For Full pAGENT (GUI Vision):${NC}"
echo -e "  1. Open chrome://extensions/"
echo -e "  2. Remove current extension"
echo -e "  3. Click 'Load unpacked'"
echo -e "  4. Select: $EXT_DIR/build/clawd-agent/"
echo -e "  5. Open side panel for browser automation"

echo -e "\n${BOLD}🤖 Claude Desktop Integration:${NC}"
echo -e "  Config written to: $CLAUDE_CONFIG_DIR/claude_desktop_config.json"
echo -e "  Restart Claude Desktop to activate MCP servers"

echo -e "\n${BOLD}🌐 OpenClawd Services:${NC}"
if [ -n "$MCP_PID" ]; then
  echo -e "  ${GREEN}✓${NC} Solana-tools MCP: PID $MCP_PID (log: $REPO_ROOT/.logs/openclawd-mcp.log)"
else
  echo -e "  ${YELLOW}○${NC} Solana-tools MCP: not started — see logs above"
fi
echo -e "  ${YELLOW}○${NC} Gateway: Connect to SolanaOS at :18790"
echo -e "  ${YELLOW}○${NC} Wallet API: Start with 'npm run ext:vault'"

echo -e "\n${BOLD}📚 Documentation:${NC}"
echo -e "  ${BLUE}→${NC} Hub: https://hub.solanaclawd.com"
echo -e "  ${BLUE}→${NC} Docs: https://docs.solanaclawd.com"
echo -e "  ${BLUE}→${NC} GitHub: https://github.com/clawdsolana/OpenClawd"

echo -e "\n${BOLD}💰 $CLAWD Token:${NC}"
echo -e "  Mint: 8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump"
echo -e "  Buy: https://pump.fun/8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump"
echo -e "  Hold $CLAWD to unlock Pro features in the extension"

echo -e "\n${PURPLE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}The Hermes of Web3 🦞 — Your keys, your agent, your rules.${NC}"
echo -e "${PURPLE}═══════════════════════════════════════════════════════════════${NC}"
