/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as WurkRouteImport } from './routes/wurk.tsx'
import { Route as WalletRouteImport } from './routes/wallet.tsx'
import { Route as UploadRouteImport } from './routes/upload.tsx'
import { Route as TrackerRouteImport } from './routes/tracker.tsx'
import { Route as TermsRouteImport } from './routes/terms.tsx'
import { Route as TerminalRouteImport } from './routes/terminal.tsx'
import { Route as StrategyRouteImport } from './routes/strategy.tsx'
import { Route as StarsRouteImport } from './routes/stars.tsx'
import { Route as SettingsRouteImport } from './routes/settings.tsx'
import { Route as SearchRouteImport } from './routes/search.tsx'
import { Route as ScannerRouteImport } from './routes/scanner.tsx'
import { Route as RugcheckRouteImport } from './routes/rugcheck.tsx'
import { Route as RegisterAgentRouteImport } from './routes/register-agent.tsx'
import { Route as PrivacyRouteImport } from './routes/privacy.tsx'
import { Route as PairRouteImport } from './routes/pair.tsx'
import { Route as MobileRouteImport } from './routes/mobile.tsx'
import { Route as MiningRouteImport } from './routes/mining.tsx'
import { Route as MemescopeRouteImport } from './routes/memescope.tsx'
import { Route as MarketplaceRouteImport } from './routes/marketplace.tsx'
import { Route as ManagementRouteImport } from './routes/management.tsx'
import { Route as LicenseRouteImport } from './routes/license.tsx'
import { Route as LaunchRouteImport } from './routes/launch.tsx'
import { Route as IpfsRouteImport } from './routes/ipfs.tsx'
import { Route as ImportRouteImport } from './routes/import.tsx'
import { Route as HubRouteImport } from './routes/hub.tsx'
import { Route as GodmodeRouteImport } from './routes/godmode.tsx'
import { Route as GatewayRouteImport } from './routes/gateway.tsx'
import { Route as EarlyAccessRouteImport } from './routes/early-access.tsx'
import { Route as DexRouteImport } from './routes/dex.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as CreateRouteImport } from './routes/create.tsx'
import { Route as CopyrightRouteImport } from './routes/copyright.tsx'
import { Route as ConsoleRouteImport } from './routes/console.tsx'
import { Route as ChessRouteImport } from './routes/chess.tsx'
import { Route as ChatRouteImport } from './routes/chat.tsx'
import { Route as StakingRouteImport } from './routes/staking.tsx'
import { Route as NewsRouteImport } from './routes/news.tsx'
import { Route as AdminRouteImport } from './routes/admin.tsx'
import { Route as AboutRouteImport } from './routes/about.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoulsIndexRouteImport } from './routes/souls/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as UHandleRouteImport } from './routes/u/$handle.tsx'
import { Route as SoulsSlugRouteImport } from './routes/souls/$slug.tsx'
import { Route as SetupTroubleshootingRouteImport } from './routes/setup/troubleshooting.tsx'
import { Route as SetupTelegramRouteImport } from './routes/setup/telegram.tsx'
import { Route as SetupMintSkillsRouteImport } from './routes/setup/mint-skills.tsx'
import { Route as SetupMiningRouteImport } from './routes/setup/mining.tsx'
import { Route as SetupMetaplexRouteImport } from './routes/setup/metaplex.tsx'
import { Route as SetupGatewayRouteImport } from './routes/setup/gateway.tsx'
import { Route as SetupExtensionRouteImport } from './routes/setup/extension.tsx'
import { Route as CliAuthRouteImport } from './routes/cli/auth.tsx'
import { Route as ChartTokenRouteImport } from './routes/chart.$token.tsx'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback.tsx'
import { Route as AgentsEngineRouteImport } from './routes/agents/engine.tsx'
import { Route as AgentsAgentRefRouteImport } from './routes/agents/$agentRef.tsx'
import { Route as OwnerSlugRouteImport } from './routes/$owner/$slug.tsx'

const WurkRoute = WurkRouteImport.update({
  id: '/wurk',
  path: '/wurk',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RugcheckRoute = RugcheckRouteImport.update({
  id: '/rugcheck',
  path: '/rugcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAgentRoute = RegisterAgentRouteImport.update({
  id: '/register-agent',
  path: '/register-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoute = MiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const MemescopeRoute = MemescopeRouteImport.update({
  id: '/memescope',
  path: '/memescope',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const IpfsRoute = IpfsRouteImport.update({
  id: '/ipfs',
  path: '/ipfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GodmodeRoute = GodmodeRouteImport.update({
  id: '/godmode',
  path: '/godmode',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessRoute = ChessRouteImport.update({
  id: '/chess',
  path: '/chess',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsIndexRoute = SoulsIndexRouteImport.update({
  id: '/souls/',
  path: '/souls/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsSlugRoute = SoulsSlugRouteImport.update({
  id: '/souls/$slug',
  path: '/souls/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTroubleshootingRoute = SetupTroubleshootingRouteImport.update({
  id: '/setup/troubleshooting',
  path: '/setup/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTelegramRoute = SetupTelegramRouteImport.update({
  id: '/setup/telegram',
  path: '/setup/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMintSkillsRoute = SetupMintSkillsRouteImport.update({
  id: '/setup/mint-skills',
  path: '/setup/mint-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMiningRoute = SetupMiningRouteImport.update({
  id: '/setup/mining',
  path: '/setup/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMetaplexRoute = SetupMetaplexRouteImport.update({
  id: '/setup/metaplex',
  path: '/setup/metaplex',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupGatewayRoute = SetupGatewayRouteImport.update({
  id: '/setup/gateway',
  path: '/setup/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupExtensionRoute = SetupExtensionRouteImport.update({
  id: '/setup/extension',
  path: '/setup/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartTokenRoute = ChartTokenRouteImport.update({
  id: '/chart/$token',
  path: '/chart/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsEngineRoute = AgentsEngineRouteImport.update({
  id: '/agents/engine',
  path: '/agents/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentRefRoute = AgentsAgentRefRouteImport.update({
  id: '/agents/$agentRef',
  path: '/agents/$agentRef',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSlugRoute = OwnerSlugRouteImport.update({
  id: '/$owner/$slug',
  path: '/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/chess': typeof ChessRoute
  '/console': typeof ConsoleRoute
  '/copyright': typeof CopyrightRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/dex': typeof DexRoute
  '/early-access': typeof EarlyAccessRoute
  '/gateway': typeof GatewayRoute
  '/godmode': typeof GodmodeRoute
  '/hub': typeof HubRoute
  '/import': typeof ImportRoute
  '/ipfs': typeof IpfsRoute
  '/launch': typeof LaunchRoute
  '/license': typeof LicenseRoute
  '/management': typeof ManagementRoute
  '/marketplace': typeof MarketplaceRoute
  '/memescope': typeof MemescopeRoute
  '/mining': typeof MiningRoute
  '/mobile': typeof MobileRoute
  '/news': typeof NewsRoute
  '/pair': typeof PairRoute
  '/privacy': typeof PrivacyRoute
  '/register-agent': typeof RegisterAgentRoute
  '/rugcheck': typeof RugcheckRoute
  '/scanner': typeof ScannerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/staking': typeof StakingRoute
  '/strategy': typeof StrategyRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/wurk': typeof WurkRoute
  '/$owner/$slug': typeof OwnerSlugRoute
  '/agents/$agentRef': typeof AgentsAgentRefRoute
  '/agents/engine': typeof AgentsEngineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chart/$token': typeof ChartTokenRoute
  '/cli/auth': typeof CliAuthRoute
  '/setup/extension': typeof SetupExtensionRoute
  '/setup/gateway': typeof SetupGatewayRoute
  '/setup/metaplex': typeof SetupMetaplexRoute
  '/setup/mining': typeof SetupMiningRoute
  '/setup/mint-skills': typeof SetupMintSkillsRoute
  '/setup/telegram': typeof SetupTelegramRoute
  '/setup/troubleshooting': typeof SetupTroubleshootingRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/agents/': typeof AgentsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/souls/': typeof SoulsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/chess': typeof ChessRoute
  '/console': typeof ConsoleRoute
  '/copyright': typeof CopyrightRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/dex': typeof DexRoute
  '/early-access': typeof EarlyAccessRoute
  '/gateway': typeof GatewayRoute
  '/godmode': typeof GodmodeRoute
  '/hub': typeof HubRoute
  '/import': typeof ImportRoute
  '/ipfs': typeof IpfsRoute
  '/launch': typeof LaunchRoute
  '/license': typeof LicenseRoute
  '/management': typeof ManagementRoute
  '/marketplace': typeof MarketplaceRoute
  '/memescope': typeof MemescopeRoute
  '/mining': typeof MiningRoute
  '/mobile': typeof MobileRoute
  '/news': typeof NewsRoute
  '/pair': typeof PairRoute
  '/privacy': typeof PrivacyRoute
  '/register-agent': typeof RegisterAgentRoute
  '/rugcheck': typeof RugcheckRoute
  '/scanner': typeof ScannerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/staking': typeof StakingRoute
  '/strategy': typeof StrategyRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/wurk': typeof WurkRoute
  '/$owner/$slug': typeof OwnerSlugRoute
  '/agents/$agentRef': typeof AgentsAgentRefRoute
  '/agents/engine': typeof AgentsEngineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chart/$token': typeof ChartTokenRoute
  '/cli/auth': typeof CliAuthRoute
  '/setup/extension': typeof SetupExtensionRoute
  '/setup/gateway': typeof SetupGatewayRoute
  '/setup/metaplex': typeof SetupMetaplexRoute
  '/setup/mining': typeof SetupMiningRoute
  '/setup/mint-skills': typeof SetupMintSkillsRoute
  '/setup/telegram': typeof SetupTelegramRoute
  '/setup/troubleshooting': typeof SetupTroubleshootingRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/agents': typeof AgentsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/souls': typeof SoulsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/chess': typeof ChessRoute
  '/console': typeof ConsoleRoute
  '/copyright': typeof CopyrightRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/dex': typeof DexRoute
  '/early-access': typeof EarlyAccessRoute
  '/gateway': typeof GatewayRoute
  '/godmode': typeof GodmodeRoute
  '/hub': typeof HubRoute
  '/import': typeof ImportRoute
  '/ipfs': typeof IpfsRoute
  '/launch': typeof LaunchRoute
  '/license': typeof LicenseRoute
  '/management': typeof ManagementRoute
  '/marketplace': typeof MarketplaceRoute
  '/memescope': typeof MemescopeRoute
  '/mining': typeof MiningRoute
  '/mobile': typeof MobileRoute
  '/news': typeof NewsRoute
  '/pair': typeof PairRoute
  '/privacy': typeof PrivacyRoute
  '/register-agent': typeof RegisterAgentRoute
  '/rugcheck': typeof RugcheckRoute
  '/scanner': typeof ScannerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/staking': typeof StakingRoute
  '/strategy': typeof StrategyRoute
  '/terminal': typeof TerminalRoute
  '/terms': typeof TermsRoute
  '/tracker': typeof TrackerRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/wurk': typeof WurkRoute
  '/$owner/$slug': typeof OwnerSlugRoute
  '/agents/$agentRef': typeof AgentsAgentRefRoute
  '/agents/engine': typeof AgentsEngineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chart/$token': typeof ChartTokenRoute
  '/cli/auth': typeof CliAuthRoute
  '/setup/extension': typeof SetupExtensionRoute
  '/setup/gateway': typeof SetupGatewayRoute
  '/setup/metaplex': typeof SetupMetaplexRoute
  '/setup/mining': typeof SetupMiningRoute
  '/setup/mint-skills': typeof SetupMintSkillsRoute
  '/setup/telegram': typeof SetupTelegramRoute
  '/setup/troubleshooting': typeof SetupTroubleshootingRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/agents/': typeof AgentsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/souls/': typeof SoulsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/chess'
    | '/console'
    | '/copyright'
    | '/create'
    | '/dashboard'
    | '/dex'
    | '/early-access'
    | '/gateway'
    | '/godmode'
    | '/hub'
    | '/import'
    | '/ipfs'
    | '/launch'
    | '/license'
    | '/management'
    | '/marketplace'
    | '/memescope'
    | '/mining'
    | '/mobile'
    | '/news'
    | '/pair'
    | '/privacy'
    | '/register-agent'
    | '/rugcheck'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/stars'
    | '/staking'
    | '/strategy'
    | '/terminal'
    | '/terms'
    | '/tracker'
    | '/upload'
    | '/wallet'
    | '/wurk'
    | '/$owner/$slug'
    | '/agents/$agentRef'
    | '/agents/engine'
    | '/auth/callback'
    | '/chart/$token'
    | '/cli/auth'
    | '/setup/extension'
    | '/setup/gateway'
    | '/setup/metaplex'
    | '/setup/mining'
    | '/setup/mint-skills'
    | '/setup/telegram'
    | '/setup/troubleshooting'
    | '/souls/$slug'
    | '/u/$handle'
    | '/agents/'
    | '/skills/'
    | '/souls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/chess'
    | '/console'
    | '/copyright'
    | '/create'
    | '/dashboard'
    | '/dex'
    | '/early-access'
    | '/gateway'
    | '/godmode'
    | '/hub'
    | '/import'
    | '/ipfs'
    | '/launch'
    | '/license'
    | '/management'
    | '/marketplace'
    | '/memescope'
    | '/mining'
    | '/mobile'
    | '/news'
    | '/pair'
    | '/privacy'
    | '/register-agent'
    | '/rugcheck'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/stars'
    | '/staking'
    | '/strategy'
    | '/terminal'
    | '/terms'
    | '/tracker'
    | '/upload'
    | '/wallet'
    | '/wurk'
    | '/$owner/$slug'
    | '/agents/$agentRef'
    | '/agents/engine'
    | '/auth/callback'
    | '/chart/$token'
    | '/cli/auth'
    | '/setup/extension'
    | '/setup/gateway'
    | '/setup/metaplex'
    | '/setup/mining'
    | '/setup/mint-skills'
    | '/setup/telegram'
    | '/setup/troubleshooting'
    | '/souls/$slug'
    | '/u/$handle'
    | '/agents'
    | '/skills'
    | '/souls'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/chess'
    | '/console'
    | '/copyright'
    | '/create'
    | '/dashboard'
    | '/dex'
    | '/early-access'
    | '/gateway'
    | '/godmode'
    | '/hub'
    | '/import'
    | '/ipfs'
    | '/launch'
    | '/license'
    | '/management'
    | '/marketplace'
    | '/memescope'
    | '/mining'
    | '/mobile'
    | '/news'
    | '/pair'
    | '/privacy'
    | '/register-agent'
    | '/rugcheck'
    | '/scanner'
    | '/search'
    | '/settings'
    | '/stars'
    | '/staking'
    | '/strategy'
    | '/terminal'
    | '/terms'
    | '/tracker'
    | '/upload'
    | '/wallet'
    | '/wurk'
    | '/$owner/$slug'
    | '/agents/$agentRef'
    | '/agents/engine'
    | '/auth/callback'
    | '/chart/$token'
    | '/cli/auth'
    | '/setup/extension'
    | '/setup/gateway'
    | '/setup/metaplex'
    | '/setup/mining'
    | '/setup/mint-skills'
    | '/setup/telegram'
    | '/setup/troubleshooting'
    | '/souls/$slug'
    | '/u/$handle'
    | '/agents/'
    | '/skills/'
    | '/souls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  ChessRoute: typeof ChessRoute
  ConsoleRoute: typeof ConsoleRoute
  CopyrightRoute: typeof CopyrightRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DexRoute: typeof DexRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  GatewayRoute: typeof GatewayRoute
  GodmodeRoute: typeof GodmodeRoute
  HubRoute: typeof HubRoute
  ImportRoute: typeof ImportRoute
  IpfsRoute: typeof IpfsRoute
  LaunchRoute: typeof LaunchRoute
  LicenseRoute: typeof LicenseRoute
  ManagementRoute: typeof ManagementRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MemescopeRoute: typeof MemescopeRoute
  MiningRoute: typeof MiningRoute
  MobileRoute: typeof MobileRoute
  NewsRoute: typeof NewsRoute
  PairRoute: typeof PairRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterAgentRoute: typeof RegisterAgentRoute
  RugcheckRoute: typeof RugcheckRoute
  ScannerRoute: typeof ScannerRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StarsRoute: typeof StarsRoute
  StakingRoute: typeof StakingRoute
  StrategyRoute: typeof StrategyRoute
  TerminalRoute: typeof TerminalRoute
  TermsRoute: typeof TermsRoute
  TrackerRoute: typeof TrackerRoute
  UploadRoute: typeof UploadRoute
  WalletRoute: typeof WalletRoute
  WurkRoute: typeof WurkRoute
  OwnerSlugRoute: typeof OwnerSlugRoute
  AgentsAgentRefRoute: typeof AgentsAgentRefRoute
  AgentsEngineRoute: typeof AgentsEngineRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChartTokenRoute: typeof ChartTokenRoute
  CliAuthRoute: typeof CliAuthRoute
  SetupExtensionRoute: typeof SetupExtensionRoute
  SetupGatewayRoute: typeof SetupGatewayRoute
  SetupMetaplexRoute: typeof SetupMetaplexRoute
  SetupMiningRoute: typeof SetupMiningRoute
  SetupMintSkillsRoute: typeof SetupMintSkillsRoute
  SetupTelegramRoute: typeof SetupTelegramRoute
  SetupTroubleshootingRoute: typeof SetupTroubleshootingRoute
  SoulsSlugRoute: typeof SoulsSlugRoute
  UHandleRoute: typeof UHandleRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SoulsIndexRoute: typeof SoulsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wurk': {
      id: '/wurk'
      path: '/wurk'
      fullPath: '/wurk'
      preLoaderRoute: typeof WurkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rugcheck': {
      id: '/rugcheck'
      path: '/rugcheck'
      fullPath: '/rugcheck'
      preLoaderRoute: typeof RugcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-agent': {
      id: '/register-agent'
      path: '/register-agent'
      fullPath: '/register-agent'
      preLoaderRoute: typeof RegisterAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memescope': {
      id: '/memescope'
      path: '/memescope'
      fullPath: '/memescope'
      preLoaderRoute: typeof MemescopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipfs': {
      id: '/ipfs'
      path: '/ipfs'
      fullPath: '/ipfs'
      preLoaderRoute: typeof IpfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godmode': {
      id: '/godmode'
      path: '/godmode'
      fullPath: '/godmode'
      preLoaderRoute: typeof GodmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess': {
      id: '/chess'
      path: '/chess'
      fullPath: '/chess'
      preLoaderRoute: typeof ChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/': {
      id: '/souls/'
      path: '/souls'
      fullPath: '/souls/'
      preLoaderRoute: typeof SoulsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/$slug': {
      id: '/souls/$slug'
      path: '/souls/$slug'
      fullPath: '/souls/$slug'
      preLoaderRoute: typeof SoulsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/troubleshooting': {
      id: '/setup/troubleshooting'
      path: '/setup/troubleshooting'
      fullPath: '/setup/troubleshooting'
      preLoaderRoute: typeof SetupTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/telegram': {
      id: '/setup/telegram'
      path: '/setup/telegram'
      fullPath: '/setup/telegram'
      preLoaderRoute: typeof SetupTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/mint-skills': {
      id: '/setup/mint-skills'
      path: '/setup/mint-skills'
      fullPath: '/setup/mint-skills'
      preLoaderRoute: typeof SetupMintSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/mining': {
      id: '/setup/mining'
      path: '/setup/mining'
      fullPath: '/setup/mining'
      preLoaderRoute: typeof SetupMiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/metaplex': {
      id: '/setup/metaplex'
      path: '/setup/metaplex'
      fullPath: '/setup/metaplex'
      preLoaderRoute: typeof SetupMetaplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/gateway': {
      id: '/setup/gateway'
      path: '/setup/gateway'
      fullPath: '/setup/gateway'
      preLoaderRoute: typeof SetupGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/extension': {
      id: '/setup/extension'
      path: '/setup/extension'
      fullPath: '/setup/extension'
      preLoaderRoute: typeof SetupExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart/$token': {
      id: '/chart/$token'
      path: '/chart/$token'
      fullPath: '/chart/$token'
      preLoaderRoute: typeof ChartTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/engine': {
      id: '/agents/engine'
      path: '/agents/engine'
      fullPath: '/agents/engine'
      preLoaderRoute: typeof AgentsEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentRef': {
      id: '/agents/$agentRef'
      path: '/agents/$agentRef'
      fullPath: '/agents/$agentRef'
      preLoaderRoute: typeof AgentsAgentRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$slug': {
      id: '/$owner/$slug'
      path: '/$owner/$slug'
      fullPath: '/$owner/$slug'
      preLoaderRoute: typeof OwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  ChessRoute: ChessRoute,
  ConsoleRoute: ConsoleRoute,
  CopyrightRoute: CopyrightRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DexRoute: DexRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  GatewayRoute: GatewayRoute,
  GodmodeRoute: GodmodeRoute,
  HubRoute: HubRoute,
  ImportRoute: ImportRoute,
  IpfsRoute: IpfsRoute,
  LaunchRoute: LaunchRoute,
  LicenseRoute: LicenseRoute,
  ManagementRoute: ManagementRoute,
  MarketplaceRoute: MarketplaceRoute,
  MemescopeRoute: MemescopeRoute,
  MiningRoute: MiningRoute,
  MobileRoute: MobileRoute,
  NewsRoute: NewsRoute,
  PairRoute: PairRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterAgentRoute: RegisterAgentRoute,
  RugcheckRoute: RugcheckRoute,
  ScannerRoute: ScannerRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StarsRoute: StarsRoute,
  StakingRoute: StakingRoute,
  StrategyRoute: StrategyRoute,
  TerminalRoute: TerminalRoute,
  TermsRoute: TermsRoute,
  TrackerRoute: TrackerRoute,
  UploadRoute: UploadRoute,
  WalletRoute: WalletRoute,
  WurkRoute: WurkRoute,
  OwnerSlugRoute: OwnerSlugRoute,
  AgentsAgentRefRoute: AgentsAgentRefRoute,
  AgentsEngineRoute: AgentsEngineRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChartTokenRoute: ChartTokenRoute,
  CliAuthRoute: CliAuthRoute,
  SetupExtensionRoute: SetupExtensionRoute,
  SetupGatewayRoute: SetupGatewayRoute,
  SetupMetaplexRoute: SetupMetaplexRoute,
  SetupMiningRoute: SetupMiningRoute,
  SetupMintSkillsRoute: SetupMintSkillsRoute,
  SetupTelegramRoute: SetupTelegramRoute,
  SetupTroubleshootingRoute: SetupTroubleshootingRoute,
  SoulsSlugRoute: SoulsSlugRoute,
  UHandleRoute: UHandleRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SoulsIndexRoute: SoulsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
